# -*- coding: utf-8 -*-
"""
/***************************************************************************
 saveAttribute
                                 A QGIS plugin
 this plugins save attributes 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-06-15
        git sha              : $Format:%H$
        copyright            : (C) 2021 by achrafCompany
        email                : achrafaouad7@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from PyQt5.QtCore import QSettings, QTranslator, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction,QFileDialog
from qgis.core import QgsProject ,Qgis
from qgis.core import *
from qgis.core.additions import processing
from qgis.utils import *
from PyQt5.QtCore import *
import processing

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .save_attribute_dialog import saveAttributeDialog
import os.path





class saveAttribute:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.list= []
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'saveAttribute_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Save Attributes')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('saveAttribute', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/save_attribute/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'save Attribute as csv '),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Save Attributes'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(
            self.dlg, "Select   output file ", "", '*.shp')
        self.dlg.lineEdit.setText(filename)

    def change_value1(self):
        selectedlistIndex = self.dlg.comboBox_2.currentIndex()
        selectedfield = self.list[selectedlistIndex]
        text = self.dlg.lineEdit_2.text()
        self.dlg.lineEdit_2.setText(" ")
        self.dlg.lineEdit_2.setText(text + selectedfield)


    def change_value(self):
        layers = QgsProject.instance().layerTreeRoot().children()
        self.dlg.comboBox_2.clear()
        # Populate the comboBox with names of all the loaded layers
        selectedLayerIndex = self.dlg.comboBox.currentIndex()
        selectedLayer = layers[selectedLayerIndex].layer()
        self.list.clear()
        for i in selectedLayer.fields():
            self.list.append(i.name())
        self.dlg.comboBox_2.addItems([field for field in self.list])
        selectedlistIndex = self.dlg.comboBox_2.currentIndex()
        selectedfield = self.list[selectedlistIndex]
        self.dlg.lineEdit_2.setText(selectedfield)

    def get_layer_by_name(self, layerName):
        # layers = QgsProject.instance().layerTreeRoot().children()
        layer = list(filter(lambda layer: (layer.name() == layerName), self.layers))
        return layer[0]

    def intersect(self):
        layer1 = self.dlg.comboBox_3.currentText()
        layer2 = self.dlg.comboBox_4.currentText()
        a=processing.run("qgis:selectbylocation", {
            "INPUT": self.get_layer_by_name(layer1),
            "PREDICATE": 0,
            "INTERSECT": self.get_layer_by_name(layer2),
            "METHOD": 0
        })
        print(a)



    def change_value12(self):
        layers = QgsProject.instance().layerTreeRoot().children()
        selectedLayerIndex = self.dlg.comboBox.currentIndex()
        selectedLayer = layers[selectedLayerIndex].layer()
        selectedLayer.selectByExpression(self.dlg.lineEdit_2.text())

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = saveAttributeDialog()
            self.dlg.pushButton.clicked.connect(self.select_output_file)

        # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()
        project = QgsProject.instance()
        project.read("myfirstproject.qgz")
        self.layers = [layer for layer in project.mapLayers().values()]
        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()


        self.dlg.comboBox.addItems([layer.name() for layer in layers])
        self.dlg.comboBox_3.addItems([layer.name() for layer in layers])
        self.dlg.comboBox_4.addItems([layer.name() for layer in layers])
        selectedLayerIndex = self.dlg.comboBox.currentIndex()

        # Populate the comboBox with names of all the loaded layers

        self.dlg.comboBox.currentIndexChanged.connect(lambda: self.change_value())
        self.dlg.comboBox_2.currentIndexChanged.connect(lambda: self.change_value1())
        #working


        self.dlg.button_box.clicked.connect(lambda: self.change_value12())
        self.dlg.pushButton_2.clicked.connect(lambda: self.intersect())




        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            filename = self.dlg.lineEdit.text()
            selectedLayerIndex = self.dlg.comboBox.currentIndex()
            selectedLayer = self.layers[selectedLayerIndex].layer()
            writer = QgsVectorFileWriter.writeAsVectorFormat(selectedLayer, self.dlg.lineEdite.text(), 'utf-8', driverName='ESRI Shapefile')
            del(writer)
